### ISSUE TITLE
能否扩展主动下拉刷新（加载更多）方法呢？

### ISSUE THREAD

**Issue by Mauiie** [wenhaiz/ComposeRefreshLayout#2]
列表有时需要主动触发刷新效果如附件视频，能否扩展主动刷新方法呢？

比如通过传递State 给RefreshLayout。

https://user-images.githubusercontent.com/11786490/234736521-2227247c-d5d2-4a54-ab3f-cde2fe7491cb.mp4

**Comment by wenhaiz** [comment]
目前还不支持，加到todo了

**Comment by Mauiie** [comment]
试了一下，RefreshLayoutState 里的startRefresh就可以实现上述效果  我本地把startRefresh方法暴露出来了

**Comment by wenhaiz** [comment]
我在 1.0.0-beta.4 支持了这个功能
